CREATE TABLE PLACES
(PLACE_ID VARCHAR(5) NOT NULL,
PLACE_NAME VARCHAR(50) NOT NULL,
PLACE_DISTANCE FLOAT(4,2) NOT NULL,
PRIMARY KEY (PLACE_ID));

INSERT INTO PLACES VALUES('HNZRS','HAZRAT NIZAMUDDIN RAILWAY STATION','45.80');
INSERT INTO PLACES VALUES('NDRLS','NEW DELHI RAILWAY STATION','53.30');
INSERT INTO PLACES VALUES('S37ND','NOIDA SECTOR 37 METRO STATION','39.40');
INSERT INTO PLACES VALUES('PCGRN','PARI CHOWK GREATER NOIDA','12.40');
INSERT INTO PLACES VALUES('GHZBD','GHAZIABAD','21.00');
INSERT INTO PLACES VALUES('AVMRS','ANAND VIHAR METRO STATION','32.80');
INSERT INTO PLACES VALUES('GURGN','GURGAON','77.90');
INSERT INTO PLACES VALUES('CONPL','CONNAUGHT PLACE','51.90');
INSERT INTO PLACES VALUES('IGIT3','TERMINAL 3 AIRPORT','51.90');